# Generated by Django 5.2.7 on 2025-10-23 08:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('accountant', 'Accountant'), ('it_manager', 'IT Manager'), ('helper', 'Helper')], default='helper', max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('cnic', models.CharField(blank=True, default='', max_length=25)),
                ('address', models.TextField(blank=True, default='')),
                ('has_software_access', models.BooleanField(default=False)),
                ('access_sales', models.BooleanField(default=False)),
                ('access_inventory', models.BooleanField(default=False)),
                ('access_accounts', models.BooleanField(default=False)),
                ('joined_on', models.DateField(blank=True, help_text='Staff registry date', null=True)),
                ('salary_start', models.DateField(blank=True, help_text='Salary starts from this date (month-wise)', null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='barkat.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'role'], name='barkat_staf_busines_a3275e_idx'), models.Index(fields=['business', 'full_name'], name='barkat_staf_busines_385e65_idx'), models.Index(fields=['phone'], name='barkat_staf_phone_f1440c_idx'), models.Index(fields=['cnic'], name='barkat_staf_cnic_c4f86d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('business', 'phone'), name='uniq_staff_business_phone_when_set'), models.UniqueConstraint(condition=models.Q(('cnic', ''), _negated=True), fields=('business', 'cnic'), name='uniq_staff_business_cnic_when_set')],
            },
        ),
    ]
