# Generated by Django 5.2.7 on 2025-10-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='barkat.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('accountant', 'Accountant'), ('it_manager', 'IT Manager'), ('helper', 'Helper')], default='helper', max_length=30),
        ),
    ]
