# Generated by Django 5.2.7 on 2025-10-23 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0005_purchaseorder_purchaseorderitem_stocktransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='barkat_purc_busines_2ae164_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='barkat_purc_status_2e7afc_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='barkat_purc_supplie_ff3eef_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorderitem',
            name='barkat_purc_purchas_0ec716_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorderitem',
            name='barkat_purc_product_5194b1_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='stock_in',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='po_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='barkat.party'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barkat.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
