# Generated by Django 5.2.7 on 2025-10-24 05:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0006_alter_purchaseorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='joined_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('in', 'In (Receipt)'), ('out', 'Out (Payment)')], db_index=True, max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('payment_source', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], db_index=True, default='cash', max_length=10)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='barkat.bankaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='barkat.business')),
                ('cashflow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_payment', to='barkat.cashflow')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='barkat.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_purchase_orders', to='barkat.payment')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='barkat.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'date'], name='barkat_paym_busines_e007b2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['party'], name='barkat_paym_party_i_edbcef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['direction'], name='barkat_paym_directi_0732a0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_source'], name='barkat_paym_payment_0690b0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderpayment',
            index=models.Index(fields=['purchase_order'], name='barkat_purc_purchas_65defb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderpayment',
            index=models.Index(fields=['payment'], name='barkat_purc_payment_876510_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderpayment',
            unique_together={('purchase_order', 'payment')},
        ),
    ]
