# Generated by Django 5.2.7 on 2025-10-24 06:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0007_alter_staff_joined_on_alter_staff_salary_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
    ]
