# Generated by Django 5.2.7 on 2025-10-24 09:46

import barkat.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0008_product_stock_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('stationery', 'Stationery'), ('maintenance', 'Maintenance'), ('software', 'Software'), ('purchase', 'Purchases/Other Items'), ('other', 'Other')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=barkat.models._expense_upload_to)),
                ('payment_source', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], db_index=True, default='cash', max_length=10)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='barkat.bankaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='barkat.business')),
                ('cashflow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expense', to='barkat.cashflow')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='barkat.party')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='barkat.purchaseorder')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='barkat.staff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['business', 'date'], name='barkat_expe_busines_7cdd3b_idx'), models.Index(fields=['business', 'category'], name='barkat_expe_busines_84c197_idx'), models.Index(fields=['payment_source'], name='barkat_expe_payment_294b6b_idx')],
            },
        ),
    ]
