# Generated by Django 5.2.7 on 2025-10-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0009_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='barkat.business'),
        ),
    ]
