# Generated by Django 5.2.7 on 2025-11-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0015_warehouse_businessstock_stockmove_warehousestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pos_printer_name',
            field=models.CharField(blank=True, help_text='Microsoft Print to PDF', max_length=200),
        ),
    ]
