# Generated by Django 5.2.7 on 2025-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0016_business_pos_printer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pos_printer_name',
            field=models.CharField(blank=True, help_text='POS80 Printer', max_length=200),
        ),
    ]
