# Generated by Django 5.2.7 on 2025-11-14 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0017_alter_business_pos_printer_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], db_index=True, default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='barkat_paym_payment_b61926_idx'),
        ),
    ]
