# Generated by Django 5.2.7 on 2025-11-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0018_payment_payment_method_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='barkat_paym_payment_b61926_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('deposited', 'Deposited')], default='', help_text='Only used for cheque payments. Pending / Deposited.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], db_index=True, default='cash', max_length=20),
        ),
    ]
