# Generated by Django 5.2.7 on 2025-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0019_remove_payment_barkat_paym_payment_b61926_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovement',
            name='is_day_closing',
            field=models.BooleanField(default=False, help_text='If checked with Deposit (Cash -> Bank), system will use current cash in hand.'),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='movement_type',
            field=models.CharField(choices=[('deposit', 'Deposit (Cash -> Bank)'), ('cheque_deposit', 'Deposit (Cheque -> Bank)'), ('withdraw', 'Withdraw (Bank -> Cash)'), ('transfer', 'Transfer (Bank -> Bank)'), ('fee', 'Bank Fee (Out)'), ('interest', 'Interest (In)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='reference_no',
            field=models.CharField(blank=True, default='', help_text='Cheque or transaction ref if any', max_length=100),
        ),
    ]
