# Generated by Django 5.2.7 on 2025-11-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0020_bankmovement_is_day_closing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='barkat.warehouse'),
        ),
    ]
