# Generated by Django 5.2.8 on 2025-12-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0021_purchaseorder_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovement',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_movements', to='barkat.party'),
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_movements', to='barkat.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='is_day_closing',
            field=models.BooleanField(default=False, help_text='If checked with Deposit (Cash -> Bank). system will use current cash in hand.'),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='movement_type',
            field=models.CharField(choices=[('deposit', 'Deposit (Cash -> Bank)'), ('cheque_deposit', 'Deposit (Cheque -> Bank)'), ('withdraw', 'Withdraw (Bank -> Cash)'), ('transfer', 'Transfer (Bank -> Bank)'), ('fee', 'Bank Fee (Out)'), ('interest', 'Bank Interest (In)'), ('cheque_payment', 'Cheque payment (Bank -> Party / Purchase Order)')], max_length=20),
        ),
    ]
