# Generated by Django 5.2.8 on 2025-12-15 09:17

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0022_bankmovement_party_bankmovement_purchase_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['business', 'order_date'], name='barkat_sale_busines_6178c0_idx'),
        ),
    ]
