# Generated by Django 5.2.8 on 2025-12-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0023_salesorder_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salesorder',
            name='barkat_sale_busines_6178c0_idx',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='order_date',
        ),
    ]
