# Generated by Django 5.2.8 on 2026-01-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0025_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('stationery', 'Stationery'), ('maintenance', 'Maintenance'), ('tea_and_lunch', 'Tea & Lunch'), ('zakat', 'Zakat'), ('shop_kharcha', 'Shop Kharcha'), ('transport', 'Transport'), ('home_kharcha', 'Home Kharcha'), ('purchase', 'Purchases/Other Items'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
