# Generated by Django 5.2.8 on 2026-01-07 07:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0026_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_products', to='barkat.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_bulk_size',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Standard weight/qty per Bulk Unit (e.g., 50.00)', max_digits=18),
        ),
    ]
