# Generated by Django 5.2.8 on 2026-01-14 09:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0027_product_bulk_uom_product_default_bulk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='size_per_unit',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='barkat.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='size_per_unit',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Multiplier to convert to base unit', max_digits=18),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Unit used for this line item', null=True, on_delete=django.db.models.deletion.PROTECT, to='barkat.unitofmeasure'),
        ),
    ]
