# Generated by Django 5.2.8 on 2026-01-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0028_purchaseorderitem_size_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card Payment'), ('cheque', 'Cheque')], db_index=True, default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
