# Generated by Django 5.2.8 on 2026-01-19 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0029_alter_payment_payment_method_alter_product_sku_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Brand/Company name (e.g., Lays, Coca-Cola)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company_name'], name='barkat_prod_company_fa2dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'company_name'], name='barkat_prod_busines_9d307f_idx'),
        ),
    ]
