# Generated by Django 5.2.8 on 2026-01-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0031_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Default business for barcode labels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settings', to='barkat.business'),
        ),
    ]
