# Generated by Django 5.2.8 on 2026-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0032_usersettings_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='business',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='business_name',
            field=models.CharField(blank=True, default='', help_text='Business name to display on barcode labels', max_length=255),
        ),
    ]
