# Generated by Django 5.2.8 on 2026-01-22 05:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0034_add_source_order_to_sales_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='size_per_unit',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='barkat.unitofmeasure'),
        ),
    ]
