# Generated by Django 5.2.8 on 2026-01-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0035_purchasereturnitem_size_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price for this item (in the unit selected). Will be converted to lower unit if bulk unit is used.', max_digits=12, null=True),
        ),
    ]
