# Generated by Django 5.2.8

from django.db import migrations, models


def add_dozen_uom(apps, schema_editor):
    UnitOfMeasure = apps.get_model("barkat", "UnitOfMeasure")
    if not UnitOfMeasure.objects.filter(code="DZ").exists():
        UnitOfMeasure.objects.create(
            name="Dozen",
            code="DZ",
            symbol="dz",
            is_active=True,
            is_deleted=False,
        )


def remove_dozen_uom(apps, schema_editor):
    UnitOfMeasure = apps.get_model("barkat", "UnitOfMeasure")
    UnitOfMeasure.objects.filter(code="DZ").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("barkat", "0036_add_sale_price_to_purchase_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="default_sale_payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("on_credit", "On Credit")],
                default="cash",
                help_text="Default payment method in Sale Order (Cash or On Credit)",
                max_length=20,
            ),
        ),
        migrations.RunPython(add_dozen_uom, remove_dozen_uom),
    ]
