# Generated by Django 5.2.8 on 2026-01-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0037_add_dozen_uom_and_default_sale_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='cancellation_password',
            field=models.CharField(blank=True, default='', help_text='Hashed password required to cancel a sale order. Set/change in User Settings. Not your login password.', max_length=128),
        ),
    ]
