# Generated by Django 5.2.8 on 2026-01-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0040_add_opening_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='divide_per_unit',
            field=models.BooleanField(default=False, help_text='If checked, this expense will be distributed across all PO items per unit'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('stationery', 'Stationery'), ('maintenance', 'Maintenance'), ('tea_and_lunch', 'Tea & Lunch'), ('zakat', 'Zakat'), ('shop_kharcha', 'Shop Kharcha'), ('transport', 'Transport'), ('home_kharcha', 'Home Kharcha'), ('freight', 'Freight/Kiraya'), ('broker', 'Broker'), ('purchase', 'Purchases/Other Items'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
