# Generated by Django 5.2.8 on 2026-01-28 09:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0041_add_po_expense_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Effective cost per unit including distributed expenses', max_digits=12),
        ),
    ]
