# Generated by Django 5.2.8 on 2026-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0043_remove_expense_divide_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('freight', 'Freight/Kiraya'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('stationery', 'Stationery'), ('maintenance', 'Maintenance'), ('tea_and_lunch', 'Tea & Lunch'), ('zakat', 'Zakat'), ('shop_kharcha', 'Shop Kharcha'), ('transport', 'Transport'), ('home_kharcha', 'Home Kharcha'), ('purchase', 'Purchases/Other Items'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
