# Generated by Django 5.2.8 on 2026-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0044_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='divide_per_unit',
            field=models.BooleanField(default=False, help_text='If checked, this expense will be distributed across all PO items per unit'),
        ),
    ]
