# Generated by Django 5.2.8 on 2026-01-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0045_expense_divide_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_sale_business',
            field=models.ForeignKey(blank=True, help_text='Default business to auto-select when creating a new Sale Order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='barkat.business'),
        ),
    ]
