# Generated by Django 5.2.8 on 2026-01-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0046_add_default_sale_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='landing_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price including distributed expenses (Landing Cost)', max_digits=12, null=True),
        ),
    ]
