# Generated by Django 5.2.8 on 2026-01-30 16:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0047_purchaseorderitem_landing_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Landed cost at time of sale', max_digits=12),
        ),
    ]
