# Generated by Django 5.2.8 on 2026-01-31 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0048_salesorderitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Checked if this expense is already paid (e.g. at the time of purchase)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_po_expenses', to='barkat.payment'),
        ),
    ]
