# Generated by Django 5.2.8 on 2026-01-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0049_expense_is_paid_expense_payment'),
    ]

    def set_is_paid_true(apps, schema_editor):
        Expense = apps.get_model('barkat', 'Expense')
        Expense.objects.all().update(is_paid=True)

    operations = [
        migrations.RunPython(set_is_paid_true),
    ]
