# Generated by Django 5.2.8 on 2026-02-02 06:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0050_set_expenses_is_paid_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_kaat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='kaat_deduction',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='is_kaat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='kaat_deduction',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Checked if this expense is already paid (e.g. at the time of purchase)'),
        ),
    ]
