# Generated by Django 5.2.8 on 2026-02-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0051_purchaseorderitem_gross_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='is_kaat',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='kaat_deduction',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='is_kaat',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='kaat_deduction',
        ),
    ]
