# Generated by Django 5.2.8 on 2026-02-02 08:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0052_remove_purchaseorderitem_gross_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_receivables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_payables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('inventory_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='barkat.business')),
            ],
            options={
                'verbose_name_plural': 'Business Summaries',
            },
        ),
    ]
