# Generated by Django 5.2.8 on 2026-02-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0053_businesssummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='cached_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='party',
            name='cached_balance_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
