# Generated by Django 5.2.8 on 2026-02-02 11:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0054_party_cached_balance_party_cached_balance_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssummary',
            name='bank_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
