# Generated by Django 5.2.8 on 2026-02-03 09:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0055_businesssummary_bank_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_receivables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_payables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Summary Stats',
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash in Hand')], default='BANK', max_length=10),
        ),
    ]
