# Generated by Django 5.2.8 on 2026-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0056_summarystats_bankaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='protect_cash_in_hand',
            field=models.BooleanField(default=False, help_text='Require password to view Cash in Hand'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='protect_inventory',
            field=models.BooleanField(default=False, help_text='Require password to view Total Inventory Value'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='protect_payables',
            field=models.BooleanField(default=False, help_text='Require password to view Total Payables'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='protect_receivables',
            field=models.BooleanField(default=False, help_text='Require password to view Total Receivables'),
        ),
    ]
