# Generated by Django 5.2.8 on 2026-02-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0057_usersettings_protect_cash_in_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business this account belongs to. If NULL, it is global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='barkat.business'),
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_movements', to='barkat.business'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='barkat.business'),
        ),
    ]
