# Generated by Django 5.2.8 on 2026-02-04 12:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0058_bankaccount_business_bankmovement_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarystats',
            name='total_inventory_valuation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
