# Generated by Django 5.2.8 on 2026-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0059_summarystats_total_inventory_valuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_external',
            field=models.BooleanField(default=False, help_text="If True, this payment was made from outside the business cash and won't affect Cash in Hand or reports."),
        ),
    ]
