# Generated by Django 5.2.8 on 2026-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0060_payment_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='protect_bank_balance',
            field=models.BooleanField(default=False, help_text='Require password to view Bank Balance'),
        ),
    ]
