# Generated by Django 5.2.8 on 2026-02-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0061_usersettings_protect_bank_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='protect_product_valuation',
            field=models.BooleanField(default=False, help_text='Require password to view Product Valuations in Product List'),
        ),
    ]
