# Generated by Django 5.2.8 on 2026-02-25 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0062_usersettings_protect_product_valuation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staff',
            name='uniq_staff_business_phone_when_set',
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_cashin_c',
            field=models.BooleanField(default=False, verbose_name='Create Cash In'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_cashin_d',
            field=models.BooleanField(default=False, verbose_name='Delete Cash In'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_cashin_r',
            field=models.BooleanField(default=False, verbose_name='Read Cash In'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_cashin_u',
            field=models.BooleanField(default=False, verbose_name='Edit Cash In'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_cashout_c',
            field=models.BooleanField(default=False, verbose_name='Create Cash Out'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_cashout_d',
            field=models.BooleanField(default=False, verbose_name='Delete Cash Out'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_cashout_r',
            field=models.BooleanField(default=False, verbose_name='Read Cash Out'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_cashout_u',
            field=models.BooleanField(default=False, verbose_name='Edit Cash Out'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_ledger_r',
            field=models.BooleanField(default=False, verbose_name='Read Ledgers'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_product_c',
            field=models.BooleanField(default=False, verbose_name='Create Product/Category'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_product_d',
            field=models.BooleanField(default=False, verbose_name='Delete Products'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_product_r',
            field=models.BooleanField(default=False, verbose_name='Read Products'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_product_u',
            field=models.BooleanField(default=False, verbose_name='Edit Products'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_purchase_c',
            field=models.BooleanField(default=False, verbose_name='Create Purchase Order'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_purchase_d',
            field=models.BooleanField(default=False, verbose_name='Delete Purchase Order'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_purchase_r',
            field=models.BooleanField(default=False, verbose_name='Read Purchase Orders'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_purchase_u',
            field=models.BooleanField(default=False, verbose_name='Edit Purchase Order'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_sale_c',
            field=models.BooleanField(default=False, verbose_name='Create Sales Invoice'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_sale_d',
            field=models.BooleanField(default=False, verbose_name='Delete Sales Invoice'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_sale_r',
            field=models.BooleanField(default=False, verbose_name='Read Sales invoices'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_sale_u',
            field=models.BooleanField(default=False, verbose_name='Edit Sales Invoice'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('business', 'phone'), name='unique_phone_per_business'),
        ),
    ]
