# Generated by Django 5.2.8 on 2026-02-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkat', '0063_remove_staff_uniq_staff_business_phone_when_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='perm_staff_c',
            field=models.BooleanField(default=False, verbose_name='Create Staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_staff_d',
            field=models.BooleanField(default=False, verbose_name='Delete Staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_staff_r',
            field=models.BooleanField(default=False, verbose_name='Read Staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_staff_u',
            field=models.BooleanField(default=False, verbose_name='Edit Staff'),
        ),
    ]
